#!/bin/bash -e

# Run conjur-env unit tests and scan with golint and vet
# Output it placed in conjur-env/output

docker run \
  -v "$(pwd)/conjur-env:/cyberark" \
  -w /cyberark \
  --rm golang \
  bash -c '''
  set -euo pipefail
  # Run golint
  go install golang.org/x/lint/golint@latest
  golint -set_exit_status ./...

  # Run go vet
  go vet ./...

  # Run unit test with coverage
  go install github.com/jstemmer/go-junit-report@latest
  mkdir -p output
  go test -coverprofile=output/c.out -v . | tee /dev/stderr | go-junit-report > output/junit.xml
  '''
