#!/bin/bash -ex

#
# Local Integration Test Runner
#
# This script will run all features marked with
# `not @integration`, which avoids the usage of a live
# remote PCF instance, or any needed credentials.
#

function finish {
  echo 'Removing environment'
  echo '-----'
  docker-compose down -v
}
trap finish EXIT

cd "$(dirname $0)"

# Set up the containers to run in their own namespace
COMPOSE_PROJECT_NAME="$(basename "$PWD")_$(openssl rand -hex 3)"
export COMPOSE_PROJECT_NAME

export BRANCH_NAME=${BRANCH_NAME:-$(git symbolic-ref --short HEAD)}

# Sets up conjur and retrieves credentials
. ./start_conjur

# Run the install script to verify compatibility
docker-compose run --rm tester ./lib/install_go.sh

# Build latest test images
docker-compose build

# Unpack latest build of buildpack
docker-compose run --rm tester ./unpack.sh

# Skip the integration tests if the Summon variables are not present
docker-compose run --rm \
    -w "/cyberark/cloudfoundry-conjur-buildpack/ci" \
    tester cucumber \
    --format pretty \
    --format junit \
    --out ./features/reports \
    --tags 'not @integration'
