#!/bin/bash -e

# shellcheck disable=SC1091
. ci/utils

announce 'Running Golint and Vet against the Conjur-Env...'
# Unit Test Runner
./ci/test_conjur-env

announce 'Running unit tests for the secrets retrieval script...'
tests/retrieve-secrets/start
